# Dependabot configuration for Evergreen Match-3 Unity Game
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "your-team"
    assignees:
      - "your-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "winston"
        update-types: ["version-update:semver-major"]
    # Allow updates to development dependencies
    allow:
      - dependency-type: "development"

  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "your-team"
    assignees:
      - "your-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "your-team"
    assignees:
      - "your-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "your-team"
    assignees:
      - "your-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for Unity packages
  - package-ecosystem: "nuget"
    directory: "/unity"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "your-team"
    assignees:
      - "your-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "unity"
      - "nuget"