#!/bin/bash

# Generate changelog from latest commit message
# This script is used by the GitHub Actions workflow to create a changelog.txt file

set -e

# Configuration
CHANGELOG_PATH="build/changelog.txt"
BUILD_NUMBER=${GITHUB_RUN_NUMBER:-1}
BUILD_ID=${GITHUB_RUN_ID:-$(date +%s)}
COMMIT_HASH=${GITHUB_SHA:-$(git rev-parse HEAD)}
COMMIT_SHORT_HASH=${COMMIT_HASH:0:7}
COMMIT_DATE=$(git log -1 --pretty=%ci 2>/dev/null || date -u +"%Y-%m-%d %H:%M:%S %z")
COMMIT_MSG=$(git log -1 --pretty=%B 2>/dev/null || echo "No commit message available")

# Create build directory if it doesn't exist
mkdir -p "$(dirname "$CHANGELOG_PATH")"

# Generate changelog content
cat > "$CHANGELOG_PATH" << EOF
Version: $BUILD_NUMBER
Build: $BUILD_ID
Commit: $COMMIT_SHORT_HASH
Date: $COMMIT_DATE

Changes:
$COMMIT_MSG

Generated by: GitHub Actions
Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
EOF

echo "Changelog generated successfully:"
echo "=================================="
cat "$CHANGELOG_PATH"
echo "=================================="

# Also create a JSON version for programmatic use
JSON_CHANGELOG_PATH="build/changelog.json"
cat > "$JSON_CHANGELOG_PATH" << EOF
{
  "version": "$BUILD_NUMBER",
  "build_id": "$BUILD_ID",
  "commit_hash": "$COMMIT_SHORT_HASH",
  "commit_date": "$COMMIT_DATE",
  "commit_message": "$COMMIT_MSG",
  "generated_at": "$(date -u +"%Y-%m-%d %H:%M:%S UTC")",
  "generated_by": "GitHub Actions"
}
EOF

echo "JSON changelog also generated: $JSON_CHANGELOG_PATH"