name: Unity Android Build

on:
  push:
    branches: [ main, master, '**/release/**', 'cursor/**' ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/unity
            Library
            Temp
          key: ${{ runner.os }}-unity-android-${{ hashFiles('unity/Assets/**', 'unity/Packages/**', 'unity/ProjectSettings/**') }}
          restore-keys: |
            ${{ runner.os }}-unity-android-

      - name: Unity - Android Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.21f1
          targetPlatform: Android
          projectPath: unity
          allowDirtyBuild: true
          # Optional keystore inputs (placeholders)
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

      - name: Upload Android build artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-build
          path: build/Android
          retention-days: 30
