name: Unity iOS Build

on:
  push:
    branches: [ main, master, '**/release/**', 'cursor/**' ]
  pull_request:

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Unity - iOS Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.21f1
          targetPlatform: iOS
          projectPath: unity
          allowDirtyBuild: true
      - name: Upload iOS Xcode project
        uses: actions/upload-artifact@v4
        with:
          name: ios-xcode
          path: build/iOS/**
      # Optional signing/build steps can follow using your Apple certificates
