name: Unity iOS Build

on:
  push:
    branches: [ main, master, '**/release/**', 'cursor/**' ]
  pull_request:

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/unity
            Library
            Temp
          key: ${{ runner.os }}-unity-ios-${{ hashFiles('unity/Assets/**', 'unity/Packages/**', 'unity/ProjectSettings/**') }}
          restore-keys: |
            ${{ runner.os }}-unity-ios-

      - name: Unity - iOS Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2024.3.0f1
          targetPlatform: iOS
          projectPath: unity-refactored
          allowDirtyBuild: true

      - name: Upload iOS Xcode project
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-xcode
          path: build/iOS
          retention-days: 30
      # Optional signing/build steps can follow using your Apple certificates
