name: Performance Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'  # Weekly on Monday at 3 AM UTC
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of performance test'
        required: true
        default: 'load'
        type: choice
        options:
        - load
        - stress
        - all

env:
  NODE_VERSION: '22'
  PERFORMANCE_THRESHOLDS:
    RESPONSE_TIME: 2000  # 2 seconds
    THROUGHPUT: 1000     # requests per second
    ERROR_RATE: 1        # 1%

jobs:
  performance-test:
    name: Performance Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Start application
      run: |
        npm start &
        sleep 15
        echo "Application started"
        # Wait for application to be ready
        timeout 30 bash -c 'until curl -f http://localhost:3000/api/health; do sleep 2; done' || echo "Health check timeout"

    - name: Install Artillery
      run: npm install -g artillery

    - name: Create performance test config
      run: |
        cat > perf-test.yml << EOF
        config:
          target: 'http://localhost:3000'
          phases:
            - duration: 60
              arrivalRate: 10
            - duration: 120
              arrivalRate: 50
            - duration: 60
              arrivalRate: 10
        scenarios:
          - name: "Performance Test"
            weight: 100
            flow:
              - get:
                  url: "/api/health"
              - get:
                  url: "/api/economy/currencies"
              - get:
                  url: "/api/economy/inventory"
        EOF

    - name: Run performance test
      run: |
        artillery run perf-test.yml --output perf-results.json
        artillery report perf-results.json || echo "Performance test completed with warnings"

    - name: Upload performance results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-results
        path: perf-results.json
        retention-days: 30

    - name: Cleanup
      if: always()
      run: |
        pkill -f "node.*src/server/index.js" || echo "No processes to kill"
        echo "Cleanup completed"

    - name: Generate performance report
      run: |
        echo "## 🚀 Performance Test Results" >> $GITHUB_STEP_SUMMARY
        echo "**Test Type:** ${{ github.event.inputs.test_type || 'load' }}" >> $GITHUB_STEP_SUMMARY
        echo "**Thresholds:**" >> $GITHUB_STEP_SUMMARY
        echo "- Response Time: < ${{ env.PERFORMANCE_THRESHOLDS.RESPONSE_TIME }}ms" >> $GITHUB_STEP_SUMMARY
        echo "- Throughput: > ${{ env.PERFORMANCE_THRESHOLDS.THROUGHPUT }} req/s" >> $GITHUB_STEP_SUMMARY
        echo "- Error Rate: < ${{ env.PERFORMANCE_THRESHOLDS.ERROR_RATE }}%" >> $GITHUB_STEP_SUMMARY